<?php

namespace AppBundle\Repository;

/**
 * BottleTypeRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BottleTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
