<?php

namespace AppBundle\Repository;

/**
 * CellarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CellarRepository extends \Doctrine\ORM\EntityRepository
{

    public function findByCellar($cellarId)
    {
        $em = $this->getEntityManager();
        $query = $em->createQuery(
            'SELECT b
              FROM AppBundle:Bottle b
              WHERE b.cellar = :cellarId'
        )->setParameter('cellarId', $cellarId);

        return $query->getResult();
    }
}
