# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value
    app.file.twig.extension.class: AppBundle\Twig\Extension\FileExtension

services:
    app.mailer:
        class: AppBundle\Model\Mailer
        arguments: ["@mailer"]

    appbundle.repository.cellar:
        class: AppBundle\Repository\CellarRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments: ['AppBundle:Cellar']

    app.file.twig.extension:
        class: %app.file.twig.extension.class%
        tags:
            - { name: twig.extension }