# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
    app.file.twig.extension.class: AppBundle\Twig\Extension\FileExtension
    cellar.entity.class: AppBundle\Entity\Cellar
    bottle.entity.class: AppBundle\Entity\Bottle

services:
    app.mailer:
        class: AppBundle\Services\Mailer
        arguments: ['@mailer']

    appbundle.repository.cellar:
        class: Doctrine\ORM\EntityRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - %cellar.entity.class%

    appbundle.repository.bottle:
        class: Doctrine\ORM\EntityRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - %bottle.entity.class%

    appbundle.cellar_manager:
        class: AppBundle\Services\CellarManager
        arguments: ['@appbundle.repository.bottle', '@appbundle.repository.cellar']

    app.file.twig.extension:
        class: %app.file.twig.extension.class%
        tags:
            - { name: twig.extension }